### ISSUE TITLE
Gamestate not detecting the game itself

### ISSUE THREAD

**Issue by chrisgchiang** [altf4/libmelee#58]
Was trying to set up libmelee today with Slippi and I'm noticing an issue where despite running the "example.py," and setting up, I was unable to get past 

`gamestate = console.step()`

it will go into console.step and then infinite loop here:

```
if event.type == enet.EVENT_TYPE_NONE:
                if polling_mode:
                    return None
```

since polling_mode is set to 0.

However, even when setting it to 1, it appears that the console is just unable to determine that the game is running at all.

I'm on a Windows 10 computer if that helps, running Python 3.7.9

Happy to provide any details, I feel like the issue raised can be a bit vague. Guess the question is how to get Python to recognize that the iso is actually running (??)

**Comment by altf4** [comment]
What exact command are you using to run the example code? You probably want to use the `-e` flag to let libmelee autoconfigure some settings in Dolphin. In case you hadn't done that.

**Comment by chrisgchiang** [comment]
right now I'm running
`python example.py -e FM-Slippi -d`

**Comment by altf4** [comment]
Have you installed the custom gecko code that's listed in the readme?

It's not strictly NEEDED but it's necessary to get menu state information out of the game.

**Comment by chrisgchiang** [comment]
hmmm that might be it. I guess what happened is that the GALE01.ini file kept getting overwritten...is there a way to force it to use the ini file in the README?

**Comment by altf4** [comment]
You're editing the wrong file. `GALE01r2.ini` not `GALE01.ini`

**Comment by altf4** [comment]
Additionally, it should be working aside from menus. If you manually select the bot's character for it and go into game, it should start multishining.

**Comment by chrisgchiang** [comment]
I was able to get it into game, it won't multishine (for some reason) but it appears that it does know that it's "IN_GAME"...the thing is I do have the GALE01r2.ini file inside of my gamesettings folder and when I click on the Defaults button in Properties it's reflected in there, but it seems that the smashbot/libmelee still can't detect the menus for some reason.

EDIT: It seems it won't multishine because it can't detect what port the bot is running on. Ugh

**Comment by altf4** [comment]
It should be under: `SLIPPI_FOLDER/Sys/GameSettings/GALE01r2.ini`. replace that whole file.

**Comment by chrisgchiang** [comment]
ahhhh okay, I put that ini file in the wrong GameSettings folder (T_T) was able to get it to traverse the menus, thats insane. 

only thing is not detecting the port now, but I think I can take that from here? lol

**Comment by altf4** [comment]
Yea, I just realized that there's a bug in the example code. Let me fix that real quick.

**Comment by altf4** [comment]
Should be fixed as of 0.19.2. The problem was with `port_detector`. It's there to help out with online matches, since in an online game, you get stuck into an arbitrary controller port. Not the one you're locally plugged into. But it shouldn't have been running for local games.
